### PR TITLE
Speed improvements and new custom settings.

### PR DESCRIPTION
**Pull request by primaryobjects**
Hi, I've added a couple of features that you may want to consider adding to the project. They mainly focus around UI speed and customization. I just needed these features for my own build and thought others might find it useful. Thanks.

The features include:

Speed improvements.
Escape key for exiting UI.

New options:
**show_error**: (true) True to enable showing errors if loading a mame rom fails. False to disable.
**filter_search**: (true) True to enable type-ahead filter searching. False to disable.
**audit_games**: (false) True to hide roms that are not available. False to show all roms in existence.
**allow_grouping**: (true) True to allow parent/child grouping of roms. False to use plain list.
**full_screen**: (false) True to enable full screen UI. False to show in window.
**background_repeat**: (true) True to use tiled wallpaper. False to not tile.
**arrow_key_paging**: (false) True to have left/right arrow keys perform page-up/page-down. False to have arrow keys jump by letter.

Config Dialog

### CODE REVIEW

**Comment by Mataniko** [comment]
adding @john-iv to review

**Comment by john-iv** [comment]
Thanks, these look like nice additions to me; the only one that gave me pause was how the audit is handled. Typically, IV/Play is used w/ baseline mame.exe, so tying to the audit mechanism that was somewhat recently grafted onto MameUI (mame_g.ini) may confuse folks who aren't using it (mameui).  

As originally designed I opted not to have audit functionality built in because it added too much scope and clrmame does a much better job at the set level than mameui did. That said, there are requests periodically for showing a game list of just the items you have.  Short of a full kick off of -verifyroms in the background and all the overhead that entails, I wonder if a simple search/'dir' for romset zips in the \roms directory and just displaying those would be sufficient. (of course then you have folks that do full merged sets vs stand alone sets). Hmm.

**Comment by Mataniko** [comment]
I have a few notes. @primaryobjects can you provide a couple of clarifications?

* Audit - We're currently looking at MAME status attribute, and if it's "good" we determine the game to be working, this commit changes this to be based on the mame_g.ini which we shouldn't depend on. I believe the status attribute is how other FE use mame to report working/non-working status. (Other values are imperfect and preliminary) So this will break hiding non-working games. We're basically getting similar functionality with the Hidden.ini file that clrmamepro generates, which is a line separated list of sets to not show at all.

* filter_search seems to duplicate the "Filter on Input" option. Am I missing something here?
* arrow_key_paging - This makes sense if the entire UI was designed for cabinets, the page up and down do the same while left and right go to the next letter.
* background_repeat - I think we should keep this, but maybe update it to be a dropdown and support  other modes like tile/stretch/center/fit/etc
* allow_grouping - I like the idea of ungrouping clones, @john-iv ?
* full_screen - This also seems targeted towards a cab setup @john-iv ? 
* show_errors - @john-iv ?

@primaryobjects You mentioned some speed improvements, can you clarify? Thank you!

**Comment by john-iv** [comment]
Audit: We don't want to lose existing functionality with determining state from attributes, correct. Does the new toggle for the mame_g.ini audit simply remove the items in the ini leaving the existing functionality intact? Like a filter? If so Matan's new hidden.ini can do that and would probably be preferable since it's tied to clrmame instead of mameui.

Arrow keys as page up page down: I can see where this would be useful in a cab setting, though that's not really IV/Play's targeted platform.  Doesn't hurt I suppose if it's a toggle and we don't lose the original functionality.  Same with:
Fullscreen and Toggle Errors (though it would seem like you'd want some indication you have an incomplete set, sounds like you're really pushing for IV/Play into a cabinet. :)).  

Ungrouping clones toggle: to just be alphabetical sounds good.

**Comment by primaryobjects** [comment]
You've got it! I was trying this in a cabinet.

So first, all of the new settings are optional and not enabled by default (except for the speed improvement). In fact, you could just hide the check-boxes from the config dialog and leave the underlying functionality for advanced users to manually turn on. Advanced users could manually edit the IV-Play.cfg file if they wish to enable any of them. I just exposed them in the config UI to make it easier to know they're there.

Here are details on the new features:

**Speed improvements**: Scrolling through the UI has been made significantly faster. You can see this in action if you hold down the Up or Down arrow keys and scroll quickly through the list.

I removed the GC.Collect() statement from Gamelist.Drawing.cs, which removes a speed bottleneck. I then added proper "using" statements around all graphics objects that implement a Dispose() interface. This should properly handle the memory clean-up, eliminating the need for GC.Collect(), and providing the speed.

**audit_games**: Correct, this reads a MAME_g.ini, to allow hiding games that are missing, incomplete, or non-functional. This is different than what the current version of IV-Play does with "Hide non-working games". This is effectively using MameUI64's "Audit all files" feature, to only show games that actually exist and are actually playable.

This feature does NOT change any existing functionality in IV-Play. That is, this is a stand-alone feature. You can use it along with the other existing settings or chose not to use it at all. In fact, I understand the hesitation about including a feature that is tied with using a 3rd-party tool to generate the file (MameUI64). While I think it *could* be worthwhile to include, you could always just hide the check-box, and leave the underlying functionality so users can enable it manually in the IV-Play.cfg file (maybe just mention it in the readme in that case).

**show_error**: In a cabinet environment, the error dialog is problematic. This allows you to skip showing the error and jump right back into the UI. I actually like this on the PC as well.

**filter_search**: I made this as a separate check-box because it interfered with scrolling through the games with the arrow keys toggled. It's actually different than "Filter on Input", meaning the underlying code affects two different places. It defaults to true, which is the existing functionality of IV-Play.

**allow_grouping, full_screen, background_repeat, arrow_key_paging**: You guys are correct on those, largely to facilitate using in a cabinet setting. Sure, making the background a drop-down with more options would be nice, but this is a start. This way, you can select a large desktop wallpaper image to use as the background, without having to re-size it for the window.

So just to summarize, these settings are all optional, and do not change existing functionality. You could pick and choose if any of these features are valuable, to leave them in the UI config dialog. Then hide any other check-boxes that you don't want to expose, leaving it for advanced users to modify the IV-Play.cfg if they wish. If the settings are documented in the Readme.md, advanced users could always find it there. *Or, at the very least, the features can remain in my fork :)*

**Comment by john-iv** [comment]
Thanks, regarding the mameui audit, last time I checked we were better at handling certain things to prevent them from being shown in our UI, like certain preventing BIOSes and devices.  

MameUI still puts many of those in the gamelist after its audit like the ZN1 BIOS for example.  So if your audit was toggled on, would those now show? Wouldn't want that.  That said, the MameUI audit is somewhat janky after all these years.  So maybe best to hide that one.

I am excited to check the performance deltas in the scrolling around you describe.

**Comment by Mataniko** [comment]
@primaryobjects Gotcha, the name filter_search is a little misleading at first, but basically it disables text navigation.

For the audit stuff, it took me a while to realize this is something generated by messui (http://messui.1emulation.com/), not mameui (http://mameui.info). I think we should omit this, and maybe down the road implement an audit function.

Everything else looks good. I think after merging I can clean up the settings window a little bit and create a new section for "cabinet mode" settings.

The settings window is getting a little complex, but we can deal with that later.

**Comment by primaryobjects** [comment]
If you enabled the new audit + the existing "Hide non-working/non-mechanical", it should still hide the BIOSes and devices. The two settings can be used together, or separate.

The relevant part is this line of [code](https://github.com/primaryobjects/IV-Play/blob/Custom_Settings/Controls/Gamelist.cs#L397) where it filters the games to show in the list.

Notice there is a separate line to check the "audit_games" flag, and then another to check "hide_mechanical_games", and another for "hide_nonworking".

You can [test](https://github.com/primaryobjects/IV-Play/archive/Custom_Settings.zip) out the fork to make sure it hides as expected. :)
Thanks.

**Comment by john-iv** [comment]
Matan, MameUI64 produces the mame_g.ini as well now when you do an audit in MameUI64.  Started last version I think, .168.

**Comment by Mataniko** [comment]
Thanks @primaryobjects I just merged this, sorry it took so long!
57d09abee9d56c61b0269a64038429664e1688c2

**Pull request closed without merging**
